# encoding: UTF-8

FROM <%= ENV.fetch('FROM') %>
MAINTAINER The Blue Beluga <admin@bluebeluga.io>

LABEL vendor="The Blue Beluga Company"
LABEL io.bluebeluga.chef-server.description="Chef Server"
LABEL io.bluebeluga.chef-server.version="<%= ENV.fetch('TAG') %>"
LABEL io.bluebeluga.chef-server.git-revision="<%= ENV.fetch('GIT_REVISION') %>"
LABEL io.bluebeluga.chef-server.release-date="<%= Time.now.strftime('%B %d, %Y %H:%M') %>"

RUN apt-get update && \
    apt-get install -y --no-install-recommends aria2

ENV CHEF_SERVER_VERSION <%= ENV.fetch 'CHEF_SERVER_VERSION' %>
ENV CHEF_SERVER_SHA256 <%= ENV.fetch 'CHEF_SERVER_SHA256' %>

ENV CHEF_CLIENT_VERSION <%= ENV.fetch 'CHEF_CLIENT_VERSION' %>
ENV CHEF_CLIENT_SHA256 <%= ENV.fetch 'CHEF_CLIENT_SHA256' %>

COPY files/install.sh /tmp/install.sh
RUN ["/bin/sh", "/tmp/install.sh"]

COPY files/init.rb /init.rb
COPY files/chef-server.rb /.chef/chef-server.rb
COPY files/logrotate /opt/opscode/sv/logrotate
COPY files/knife.rb /etc/chef/knife.rb
COPY files/backup.sh /usr/local/bin/chef-server-backup

ENV KNIFE_HOME /etc/chef

RUN apt-get -y autoremove aria2 && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

EXPOSE 80 443
VOLUME /var/opt/opscode

CMD ["/opt/opscode/embedded/bin/ruby", "/init.rb"]
